# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster = {
  "orka-master" => { :ip => "10.98.76.80", :cpus => 1, :mem => 1024 },
  "orka-node-1" => { :ip => "10.98.76.81", :cpus => 1, :mem => 1024 },
  "orka-node-2" => { :ip => "10.98.76.82", :cpus => 1, :mem => 1024 }
}

Vagrant.configure("2") do |config|

  # Vagrant friendly version of CoreOS.
  config.vm.box = "yungsang/coreos"
  config.vm.box_check_update = true

  # CoreOS Specific settings.
  config.vbguest.auto_update = false

  # New feature of Vagrant 2.2.0 :-)
  config.vagrant.plugins = ["vagrant-hostmanager"]

  cluster.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |cfg|
      cfg.vm.hostname = hostname
      cfg.vm.network :private_network, ip: "#{info[:ip]}"

      cfg.vm.provider :virtualbox do |vb, override|
        vb.name = hostname
        vb.customize [
            "modifyvm", :id,
            "--memory", info[:mem],
            "--cpus", info[:cpus]
        ]
      end

      cfg.hostmanager.aliases = [hostname]
    end
  end
end
